/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabriel
 */
public class Aluno_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Aluno_GUI
     */
    public Aluno_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rm_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        turma_txt = new javax.swing.JTextField();
        cadastrar_btn = new javax.swing.JButton();
        consultar_btn = new javax.swing.JButton();
        alterar_btn = new javax.swing.JButton();
        excluir_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Aluno");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 30, 100, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("RM:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(193, 130, 70, 30);

        rm_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rm_txtActionPerformed(evt);
            }
        });
        jPanel1.add(rm_txt);
        rm_txt.setBounds(280, 120, 290, 50);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("NOME:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 220, 60, 30);
        jPanel1.add(nome_txt);
        nome_txt.setBounds(280, 210, 290, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("TURMA:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 310, 70, 24);
        jPanel1.add(turma_txt);
        turma_txt.setBounds(280, 300, 290, 50);

        cadastrar_btn.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar_btn.setText("CADASTRAR");
        cadastrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar_btn);
        cadastrar_btn.setBounds(70, 390, 140, 70);

        consultar_btn.setBackground(new java.awt.Color(255, 255, 255));
        consultar_btn.setText("CONSULTAR");
        consultar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(consultar_btn);
        consultar_btn.setBounds(240, 390, 140, 70);

        alterar_btn.setBackground(new java.awt.Color(255, 255, 255));
        alterar_btn.setText("ALTERAR");
        alterar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(alterar_btn);
        alterar_btn.setBounds(410, 390, 140, 70);

        excluir_btn.setBackground(new java.awt.Color(255, 255, 255));
        excluir_btn.setText("EXCLUIR");
        excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_btnActionPerformed(evt);
            }
        });
        jPanel1.add(excluir_btn);
        excluir_btn.setBounds(580, 390, 140, 70);

        sair_btn.setBackground(new java.awt.Color(255, 255, 255));
        sair_btn.setText("x");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(700, 10, 90, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rm_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rm_txtActionPerformed

    private void alterar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btnActionPerformed
        model.CRUD_DAO.alterarALuno();
    }//GEN-LAST:event_alterar_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        dispose();
    }//GEN-LAST:event_sair_btnActionPerformed

    private void cadastrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_btnActionPerformed
        model.CRUD_DAO.cadastrarAluno();
    }//GEN-LAST:event_cadastrar_btnActionPerformed

    private void consultar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_btnActionPerformed
        model.CRUD_DAO.consultarAluno();
    }//GEN-LAST:event_consultar_btnActionPerformed

    private void excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_btnActionPerformed
        model.CRUD_DAO.excluirAluno();
    }//GEN-LAST:event_excluir_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar_btn;
    private javax.swing.JButton cadastrar_btn;
    private javax.swing.JButton consultar_btn;
    private javax.swing.JButton excluir_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField nome_txt;
    public static javax.swing.JTextField rm_txt;
    private javax.swing.JButton sair_btn;
    public static javax.swing.JTextField turma_txt;
    // End of variables declaration//GEN-END:variables
}
